---
# This playbook install aws role.

- name: creating aws directory
  file:
    path: "{{ testing_dir }}"
    state: directory
  tags: install

- name: check directory exists
  stat:
    path: "{{ testing_dir }}"
  register: dir

- fail:
    msg: "Testing directory {{ testing_dir }} does not exist!"
  when: dir.stat.exists is not defined or dir.stat.isdir is not defined